// This model was generated by Forest CLI. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models

module.exports = (mongoose, Mongoose) => {
  // This section contains the properties of your model, mapped to your collection's properties.
  // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
  const schema = Mongoose.Schema({
    'email': String,
    'account': {
      'username': String,
      'phone': String,
      'avatar': {
        'asset_id': String,
        'public_id': String,
        'version': Number,
        'version_id': String,
        'signature': String,
        'width': Number,
        'height': Number,
        'format': String,
        'resource_type': String,
        'created_at': String,
        'bytes': Number,
        'type': String,
        'etag': String,
        'placeholder': Boolean,
        'url': String,
        'secure_url': String,
        'original_filename': String,
        'api_key': String,
      },
    },
    'token': String,
    'hash': String,
    'salt': String,
  }, {
    timestamps: false,
  });

  return mongoose.model('users', schema, 'users');
};
